///* DO NOT EDIT THIS FILE - it is machine generated */
//#include <jni.h>
///* Header for class com_ozcangroup_other_DoImageProcessing */
//
//#ifndef _Included_com_ozcangroup_other_DoImageProcessing
//#define _Included_com_ozcangroup_other_DoImageProcessing
//#ifdef __cplusplus
//extern "C" {
//#endif
///*
// * Class:     com_ozcangroup_other_DoImageProcessing
// * Method:    ImageProcessing
// * Signature: (II[B[IS)Z
// */
//jint
//Java_com_ozcangroup_other_DoImageProcessing_ImageProcessing(
//    JNIEnv* env, jobject thiz,
//    jint width, jint height,
//    jbyteArray NV21FrameData, jintArray outPixels, jshortArray angle)
//
//#ifdef __cplusplus
//}
//#endif
//#endif
